# Generated by Django 2.2.7 on 2019-12-01 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('img', models.ImageField(upload_to='items/')),
                ('size', models.CharField(max_length=50)),
                ('price1', models.CharField(max_length=100)),
                ('price2', models.CharField(max_length=100)),
                ('button_ym', models.CharField(max_length=250)),
            ],
        ),
    ]
